#!/usr/bin/bash
if [ -f /etc/os-release ]; then
    # freedesktop.org and systemd
    . /etc/os-release
    OS=${PRETTY_NAME:-"$NAME $VERSION_ID"}
elif type lsb_release >/dev/null 2>&1; then
    # linuxbase.org
    OS="$(lsb_release -si) $(lsb_release -sr)"
elif [ -f /etc/lsb-release ]; then
    # For some versions of Debian/Ubuntu without lsb_release command
    . /etc/lsb-release
    OS="$DISTRIB_ID $DISTRIB_RELEASE"
elif [ -f /etc/debian_version ]; then
    # Older Debian/Ubuntu/etc.
    OS="Debian $(cat /etc/debian_version)"
elif [ -f /etc/SuSe-release ]; then
    # Older SuSE/etc.
    OS=SuSE
elif [ -f /etc/redhat-release ]; then
    # Older Red Hat, CentOS, etc.
    OS=$(cat /etc/redhat-release)
else
    # Fall back to uname, e.g. "Linux", also works for BSD, etc.
    OS=$(uname -s)
fi
if [ -n "$CONTAINER_NAME" ]; then
    OS="$OS $PROMPT_CONTAINER"
fi

if command -v rpm-ostree > /dev/null; then
    BOOTC_JSON=$(rpm-ostree status --json)
    BOOTC_IMAGE=$(echo "$BOOTC_JSON" | jq -r '.deployments.[] | select (.booted == true)."container-image-reference"')
    BOOTC_IMAGE_VERSION=$(echo "$BOOTC_JSON" | jq -r '.deployments.[] | select (.booted == true)'.version)
fi